### ISSUE TITLE
ZXingObjC/ZXingObjC.h' file not found

### ISSUE THREAD

**Issue by Aquazee** [januslo/react-native-bluetooth-escpos-printer#91]
Pod Installed react-native-bluetooth-escpos-printer 0.0.5 after running gives error ZXingObjC/ZXingObjC.h' file not found.

tried Installing pod from react-native-bluetooth-escpos-printer/ios/ZXingObjC-3.2.2. 
New Error found : 
![Screenshot 2020-02-22 at 11 13 49 PM](https://user-images.githubusercontent.com/50393935/75096794-093cfa00-55c9-11ea-8d67-4ba1c8354e59.png)

Tried installing new  version of ZXingObjC but still it doesnt work. 
Thanks in Advance

**Comment by januslo** [comment]
Sorry, I may got no time on this plugin recently. May i have you help to figure out what is the issue in finding the header files? have you try to set "yes" to "Always Search User Pahts "? or some setting issue at searching the headers of the xcode? 
One thing more, running at emulator may cause building issues.

发自我的iPhone

**Comment by firdaussoberi** [comment]
I don't remember how I solved the issue long time ago (am using v0.0.5).
I think I explicitly change the import line in RNBluetoothEscposPrinter.m
from ```#import "ZXingObjC/ZXingObjC.h" ```to #import ```"ZXingObjC-3.2.2/ZXingObjC/ZXingObjC.h"``` ,something like that.

**Comment by firdaussoberi** [comment]
Oh one more thing. In older version I think there's no podspec, mine looks like this (I name it ```react-native-bluetooth-escpos-printer.podspec```, put it outside of ios folder where the react-native-bluetooth-escpos-printer in node_modules lives) :

```shell
Pod::Spec.new do |s|
  s.name         = "react-native-bluetooth-escpos-printer"
  s.version      = "0.0.5"
  s.summary      = "RNBluetoothEscposPrinter"
  s.description  = "Escpos, tsc bluetooth thermal printer."
  s.homepage     = "https://github.com/januslo/react-native-bluetooth-escpos-printer"
  s.license      = "MIT"
  s.author       = { "author" => "author@domain.cn" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/author/react-native-bluetooth-escpos-printer.git", :tag => "master" }

  s.source_files = "ios/**/*.{h,m}"

  s.dependency "React"
end
```

**Comment by Aquazee** [comment]
Ran "pod deintegrate" => Deleted Podfile.lock => pod install . Issue was resolved but new issue found now
![Simulator Screen Shot - iPhone 6s - 2020-02-24 at 22 28 45](https://user-images.githubusercontent.com/50393935/75173561-1555c280-5755-11ea-8055-6d7fe2d4dd16.png)

**Comment by Aquazee** [comment]
> @Aquazee I don't remember how I solved the issue long time ago (am using v0.0.5, also using pod).
> I think I explicitly changed the import line in RNBluetoothEscposPrinter.m
> from `#import "ZXingObjC/ZXingObjC.h" `to `#import "ZXingObjC-3.2.2/ZXingObjC/ZXingObjC.h"` ,something like that.

Such an simple solution. Did the trick

**Comment by ujangmisbah** [comment]
> @Aquazee I don't remember how I solved the issue long time ago (am using v0.0.5, also using pod).
> I think I explicitly changed the import line in RNBluetoothEscposPrinter.m
> from `#import "ZXingObjC/ZXingObjC.h" `to `#import "ZXingObjC-3.2.2/ZXingObjC/ZXingObjC.h"` ,something like that.

thanks this worked

**Comment by usfslk** [comment]
I have made those changes but the problem still persist, build failed error:

> CompileC /var/root/Library/Developer/Xcode/DerivedData/printapp3-bdgcuaoitzijpkgdxzcqqilqaxei/Build/Intermediates.noindex/ZXingObjC.build/Debug-iphonesimulator/ZXingObjC-iOS.build/Objects-normal/x86_64/ZXResultParser.o /Users/master/Desktop/biolime/cfprint/node_modules/react-native-bluetooth-escpos-printer/ios/ZXingObjC-3.2.2/ZXingObjC/client/result/ZXResultParser.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'ZXingObjC-iOS' from project 'ZXingObjC')
> (1 failure)

in Xcode there's this other issue with `stringByReplacingPercentEscapesUsingEncoding` [issue #183](https://github.com/januslo/react-native-bluetooth-escpos-printer/issues/183)

![Screen Shot 2022-04-21 at 3 53 18 AM (2)](https://user-images.githubusercontent.com/24628046/164500156-688c3cf9-2126-4636-a681-6fb15efd694a.png)
